version: '3.8'
services:
  auth:
    build:
      context: ./applications/auth
      dockerfile: ./Dockerfile
    container_name: auth
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=auth

  user:
    build:
      context: ./applications/user
      dockerfile: ./Dockerfile
    container_name: user
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=user

  game:
    build:
      context: ./applications/game
      dockerfile: ./Dockerfile
    container_name: game
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=game

  market:
    build:
      context: ./applications/market
      dockerfile: ./Dockerfile
    container_name: market
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=market

  room:
    build:
      context: ./applications/room
      dockerfile: ./Dockerfile
    container_name: room
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=room

  card:
    build:
      context: ./applications/card
      dockerfile: ./Dockerfile
    container_name: card
    ports:
      - "8086:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=card
