version: '3.8'
services:
  auth:
    build:
      context: ./applications/auth
      dockerfile: Dockerfile
    container_name: auth
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=auth
    networks:
      - mynetwork

  user:
    build:
      context: ./applications/user
      dockerfile: Dockerfile
    container_name: user
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=user
    networks:
      - mynetwork

  game:
    build:
      context: ./applications/game
      dockerfile: Dockerfile
    container_name: game
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=game
    networks:
      - mynetwork

  market:
    build:
      context: ./applications/market
      dockerfile: Dockerfile
    container_name: market
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=market
    networks:
      - mynetwork

  room:
    build:
      context: ./applications/room
      dockerfile: Dockerfile
    container_name: room
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=room
    networks:
      - mynetwork

  card:
    build:
      context: ./applications/card
      dockerfile: Dockerfile
    container_name: card
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=card
    networks:
      - mynetwork

  frontend:
    build:
      context: ./full-front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  nginx:
    build:
      context: ./reverseproxy
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - auth
      - user
      - game
      - market
      - room
      - card
      - frontend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
