version: '3.8'
services:
  Auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Auth
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=Auth

  User:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: User
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=User

  Game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Game
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=Game

  Market:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Market
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=Market

  Room:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Room
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=Room

  Card:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Card
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=Card
