version: '3.8'
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=app1

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app2
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=app2

  app3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app3
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=app3

  app4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app4
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=app4

  app5:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app5
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=app5
